// Generated by CoffeeScript 1.8.0
(function() {
  exports.createHash = require('crypto-browserify/create-hash');

  exports.createHmac = require('crypto-browserify/create-hmac');

  require('crypto-browserify/node_modules/browserify-aes/inject')(exports, exports);

}).call(this);
